// The single dictionary of Russian UI copy. Components never inline user-facing text.

export const strings = {
  app: {
    name: 'aitu dating',
  },
  time: {
    now: 'сейчас',
    minutes: 'мин',
    hours: 'ч',
    days: 'д',
  },
  tabs: {
    index: 'Главная',
    search: 'Поиск',
    create: 'Создать',
    activity: 'Активность',
    profile: 'Профиль',
  },
  home: {
    brand: 'aitu dating',
    descriptorGuest: 'preview сообщества',
    descriptorMember: 'verified conversations',
    join: 'Вступить',
    about: 'О продукте',
    filtersLabel: 'Фильтры ленты',
    cityLabel: 'Город',
    tabs: {
      for_you: 'Для тебя',
      popular: 'Популярное',
      city: 'В городе',
      plans: 'Планы',
      following: 'Подписки',
    },
  },
  feed: {
    emptyTitle: 'Здесь пока тихо',
    emptyCity: 'В этом городе пока нет публикаций. Посмотрите, о чём говорят в других городах.',
    emptyDefault: 'Публикаций по этому фильтру пока нет.',
    emptyAction: 'Показать ленту «Для тебя»',
    errorTitle: 'Не удалось загрузить ленту',
    errorNetwork: 'Проверьте подключение и попробуйте ещё раз.',
    errorDefault: 'Что-то пошло не так. Попробуйте ещё раз.',
    retry: 'Повторить',
    loadingMore: 'Загружаем ещё',
    endOfFeed: 'Вы всё посмотрели',
  },
  post: {
    type: {
      post: 'Пост',
      question: 'Вопрос',
      quote: 'Цитата',
      plan: 'План встречи',
    },
    showMore: 'Показать полностью',
    verified: 'verified',
    media: 'Изображение к публикации',
    authorSafe: (gender: string, age: number) => `${gender}, ${age}`,
    actions: {
      comment: (n: number) => `Комментарии: ${n}`,
      reaction: (n: number) => `Нравится: ${n}`,
      repost: (n: number) => `Репосты: ${n}`,
      quote: 'Цитировать',
    },
  },
  plan: {
    minutes: (n: number) => `${n} мин`,
    publicPlace: 'Публичное место',
    matched: 'Уже есть пара',
  },
  settings: {
    title: 'Настройки',
    open: 'Настройки',
    close: 'Закрыть',
    appearance: 'Оформление',
    theme: {
      system: 'Системная',
      light: 'Светлая',
      dark: 'Тёмная',
    },
    themeHint: 'Системная тема следует настройке телефона.',
  },
  demo: {
    title: 'Demo controls',
    hint: 'Только в демо-сборке. Помогают проверить ошибки и пустые состояния.',
    reset: 'Сбросить демо',
    resetDone: 'Демо сброшено: вы снова в режиме preview.',
    networkErrorOnce: 'Ошибка сети один раз',
    networkErrorOnceHint: 'Следующий запрос данных завершится ошибкой.',
    networkErrorArmed: 'Следующий запрос завершится ошибкой сети.',
    offline: 'Режим offline',
    offlineHint: 'Все запросы данных получают ошибку сети, пока режим включён.',
  },
  offline: {
    banner: 'Нет сети. Показываем сохранённые данные.',
  },
  storage: {
    resetNotice: 'Сохранённые данные устарели, демо сброшено до начального состояния.',
  },
  access: {
    close: 'Закрыть',
    back: 'Назад',
    next: 'Далее',
    step: (n: number, total: number) => `Шаг ${n} из ${total}`,
    prompt: {
      title: 'Только для участников',
      create: 'Публиковать посты и планы встреч могут участники сообщества.',
      activity: 'Ответы, реакции и события появятся после вступления.',
      profile: 'Вступите через Aitu Passport, чтобы создать свою карточку.',
      action: 'Вступить',
    },
    passport: {
      title: 'Вход через Aitu Passport',
      text: 'Выберите тестовую личность. Имя, возраст, пол и город приходят из Passport и не редактируются.',
      readOnly: 'Данные Passport только для чтения',
      subject: (id: string) => `Passport subject: ${id}`,
      candidate: (name: string, age: number, gender: string, city: string) =>
        `${name}, ${age} · ${gender} · ${city}`,
      error: 'Не удалось загрузить личности Passport.',
    },
    rules: {
      title: 'Правила клуба',
      version: 'Версия clubRules.v1 — черновик, финальный текст утвердит юрист.',
      items: [
        'Мы знакомимся через разговоры, вопросы и безопасные планы, а не через свайпы.',
        'Уважайте границы: без давления, оскорблений и навязчивых сообщений.',
        'Первая встреча — только в публичном месте.',
        'Не делитесь внешними контактами до взаимного доверия.',
        'Жалобы и блокировки рассматривает модерация; нарушения ведут к ограничению доступа.',
      ],
      accept: 'Я прочитал(а) правила и принимаю их',
      acceptRequired: 'Чтобы продолжить, подтвердите правила.',
    },
    membership: {
      title: 'Membership',
      text: 'Один уровень доступа: без доплат за сообщения, реакции и планы. Выберите ровно один вариант.',
      paidGroup: 'Платный доступ',
      freeGroup: 'Бесплатно',
      months: (n: number) => `${n} ${n === 1 ? 'месяц' : n < 5 ? 'месяца' : 'месяцев'}`,
      price: (kzt: number) => `${kzt.toLocaleString('ru-RU')} ₸`,
      bestValue: 'Выгоднее',
      free: 'Бесплатный verified',
      freeHint: '12 месяцев для demo и одобренного beta-доступа',
      chooseRequired: 'Выберите вариант membership.',
    },
    payment: {
      title: 'Оплата (демо)',
      text: 'Это демонстрационная оплата: реквизиты карты не запрашиваются, деньги не списываются.',
      summary: (months: string) => `Membership на ${months}`,
      pay: 'Оплатить (демо)',
      processing: 'Обрабатываем оплату…',
      failed:
        'Оплата не прошла. Проверьте соединение и попробуйте ещё раз — повторный запрос не спишет деньги дважды.',
      retry: 'Повторить оплату',
    },
    profileStep: {
      title: 'Анкета',
      text: 'Membership подтверждён. Заполнение карточки и 7 вопросов появятся в следующем шаге разработки.',
    },
    errors: {
      network: 'Нет соединения. Попробуйте ещё раз.',
      conflict: 'Этот шаг сейчас недоступен. Вернёмся к нужному шагу.',
      default: 'Не получилось. Попробуйте ещё раз.',
    },
  },
  stub: {
    back: 'Назад',
    access: {
      title: 'Вступление',
      text: 'Здесь появится вход через Aitu Passport, выбор membership и анкета.',
    },
    about: {
      title: 'О продукте',
      text: 'Aitu Dating — закрытое verified-сообщество, где знакомство начинается с разговора, вопроса или безопасного плана встречи, а не со свайпа.',
    },
  },
  placeholder: {
    home: {
      title: 'Главная',
      text: 'Здесь появится лента разговоров, вопросов и планов.',
    },
    search: {
      title: 'Поиск',
      text: 'Здесь появится поиск по темам, городам, постам и планам.',
    },
    create: {
      title: 'Создать',
      text: 'Здесь можно будет создать пост или встречу один на один.',
    },
    activity: {
      title: 'Активность',
      text: 'Здесь появятся ответы, реакции, подписки и события планов.',
    },
    profile: {
      title: 'Профиль',
      text: 'Здесь появятся ваша карточка, публикации, планы и настройки.',
    },
  },
  uiKit: {
    title: 'Компоненты',
    open: 'Открыть витрину компонентов',
    back: 'Назад',
    primary: 'Основная кнопка',
    secondary: 'Вторичная кнопка',
    text: 'Текстовая кнопка',
    disabled: 'Недоступна',
    loading: 'Загрузка',
    iconAction: 'Действие-иконка',
    sections: {
      default: 'Обычное состояние',
      disabled: 'Недоступно',
      loading: 'Загрузка',
      icon: 'Иконки',
    },
  },
} as const;
